### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by sanxiyn** [OmniSharp/atom-languageclient#1]
Failed to load the atom-languageclient package

Cannot find module '/home/sanxiyn/.atom/packages/atom-languageclient/dist/index'

**Comment by dgolovin** [comment]
1. Install package from Settings/Install
2. Observe message balloon with error 

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-languageclient](https://github.com/OmniSharp/atom-languageclient) package, v1.0.7


### Stack Trace

Failed to load the atom-languageclient package

```
At Cannot find module 'C:\Users\eskimo\.atom\packages\atom-languageclient\dist\index'

Error: Cannot find module 'C:\Users\eskimo\.atom\packages\atom-languageclient\dist\index'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\eskimo\.atom\packages\atom-languageclient\index.js:7:22)
    at Module._compile (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .js] (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:747:27)
    at C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:118:28
    at Package.module.exports.Package.measure (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:548:30)
    at C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:439:29
    at exit (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\buffered-process.js:229:18
    at Socket.<anonymous> (C:\Users\eskimo\AppData\Local\atom\app-1.12.7\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -5:17.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:11.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -5:04.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:55.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:57.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:53.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "update-package-dependencies"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-languageclient, v1.0.7 (inactive)
compare-files, v0.8.0 (active)
gulp-control, v0.5.0 (inactive)
language-powershell, v4.0.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
linter-write-good, v0.8.0 (active)
npm-outdated, v0.6.0 (active)
xml-formatter, v0.10.0 (inactive)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by amand1996** [comment]
This can be resolved by changing index.js (index.js in the root directory) from 
module.exports = require(path.join(__dirname, 'dist/index')); 
to 
module.exports = require(path.join(__dirname, 'dist/src/index'));

The error occurs because there is no index file in dist. Seems this should work. But it raises another issue as SelectListView.ts is unable to find '../../../styles/select-list.less'. Even if you resolve this problem, by specifying the correct path, you face another error "vscode_jsonrpc_1.RequestType is not a constructor". There is a series of errors from bad paths to some module errors.

**Comment by krocebow** [comment]
This error is still occurring, any solution?

**Comment by prabhugopal** [comment]
@amand1996 thanks for your suggestions. Its really helped me to cracked down this issue.

I am able to fix this issue as follows,

Seems the modules "vscode-jsonrpc" version (2.2.0) bundled with "atom-languageclient" doesn't not compatible with this package. So I copied the proper "vscode-jsonrpc" module version (3.3.1) which came along with "ide-java" package, as a dirty fix.  For your reference I have included the files, unzip and copy the files into the (**..atom-languageclient\node_modules**) and try opening the atom.

[vscode-jsonrpc.zip](https://github.com/OmniSharp/atom-languageclient/files/1301611/vscode-jsonrpc.zip)

This is a temporary workaround until we get the solution.

@krocebow, to fix this issue we need to follow 2 steps specified by @amand1996

1. Change the following code in index.js (under the package root directory.  [.atom\packages\atom-languageclient] )

```
//from
else {
    module.exports = require(path.join(__dirname, 'dist/index'));
}

//to 
else {
    module.exports = require(path.join(__dirname, 'dist/src/index'));
}
```

2. Update the code in **.atom/packages/atom-languageclient/dist/src/atom/views/SelectListView.js** as follows.

```
//from
atom.themes.requireStylesheet(require.resolve('../../../styles/select-list.less'));

//to
atom.themes.requireStylesheet(require.resolve('../../../../styles/select-list.less'));
```
3. Download the attached "vscode-jsonrpc" module zip, unzip and copy into the node-modules of this package. (**.atom/packages/atom-languageclient/node_modules**). Please backup the old folder.

Also i have requested all these updates to repository to get the proper fix for this issue.

**Comment by ethikz** [comment]
@prabhugopal I did as outlined and I am getting this error now

```
TypeError: vscode_jsonrpc_1.RequestType is not a constructor
    at exports.RegistrationRequest.exports.RegistrationRequest (/Users/Josh/.atom/packages/atom-languageclient/node_modules/atom-languageservices/protocol.js:13:32)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/node_modules/atom-languageservices/protocol.js:14:3)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/node_modules/atom-languageservices/protocol.js:421:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom%20Beta.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/dist/src/protocol/Connection.js:11:18)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/dist/src/protocol/Connection.js:205:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom%20Beta.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/dist/src/language/LanguageProvider.js:17:20)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/dist/src/language/LanguageProvider.js:111:3)
    at Module.get_Module._compile (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom%20Beta.app/Contents/Resources/app.asar/static/index.js:47:45)
    at require (/Applications/Atom Beta.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/dist/src/language/index.js:10:10)
    at Object.<anonymous> (/Users/Josh/.atom/packages/atom-languageclient/dist/src/language/index.js:13:3)
```

**Comment by prabhugopal** [comment]
@ethikz 

Did you unzip & copy the module https://github.com/OmniSharp/atom-languageclient/files/1301611/vscode-jsonrpc.zip into the node-modules **(.atom/packages/atom-languageclient/node_modules)** ?. Please rename the old vscode-jsonrpc folder before copying it.

**Comment by ethikz** [comment]
@prabhugopal Yes but I didn't see where you changed the package version so I did that and removed `node_modules` and reinstalling everything for that package then will recopy the folder to it.

Actually changing the version in the `package.json` and recopying the `vscode-jsonrpc` into `node_modules` fixed it.

Thanks!  👍

**Comment by prabhugopal** [comment]
@ethikz Welcome.  :+1:
