### ISSUE TITLE
Failed to load the atom-languageclient package

### ISSUE THREAD

**Issue by Khady** [OmniSharp/atom-languageclient#4]
When I launch atom, I have this error message:

> Failed to load the atom-languageclient package

Details:

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Debian GNU/Linux
**Thrown From**: [atom-languageclient](https://github.com/OmniSharp/atom-languageclient) package, v1.0.7

### Stack Trace

Failed to load the atom-languageclient package

```
At Cannot find module '/home/louis/.atom/packages/atom-languageclient/dist/index'

Error: Cannot find module '/home/louis/.atom/packages/atom-languageclient/dist/index'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/louis/.atom/packages/atom-languageclient/index.js:7:22)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:109:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:766:27)
    at /usr/share/atom/resources/app.asar/src/package.js:121:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:94:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:108:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:468:14)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/usr/share/atom/resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:407:19)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:811:28
```

### Commands

```
     -0:00.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "vim-mode",
      "ex-mode",
      "tree-ignore",
      "revert-buffer",
      "terminal-plus",
      "language-source-cfg",
      "tabs",
      "smart-tags",
      "emacs-plus"
    ],
    "packagesWithKeymapsDisabled": [
      "find-and-replace",
      "trailing-semicolon",
      "highlight-line"
    ],
    "projectHome": "/home/louis/Code",
    "telemetryConsent": "no"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.5 (inactive)
atom-languageclient, v1.0.7 (inactive)
autocomplete-paths, v1.0.5 (inactive)
autocomplete-python, v1.8.26 (inactive)
build, v0.67.0 (inactive)
build-make, v0.13.0 (inactive)
busy, v0.7.0 (inactive)
chester-atom-syntax, v0.1.1 (inactive)
clipboard-plus, v0.5.1 (inactive)
disable-keybindings, v0.6.0 (inactive)
emacs-plus, v0.11.1 (inactive)
file-icons, v2.0.9 (inactive)
filesize, v2.0.3 (inactive)
git-time-machine, v1.5.4 (inactive)
highlight-line, v0.12.0 (inactive)
highlight-selected, v0.12.0 (inactive)
hyperclick, v0.0.39 (inactive)
language-docker, v1.1.7 (inactive)
language-ocaml, v1.1.2 (inactive)
linter, v1.11.21 (inactive)
linter-docker, v0.1.4 (inactive)
linter-flake8, v2.1.4 (inactive)
linter-jshint, v3.0.2 (inactive)
loaded, v0.3.0 (inactive)
minimap, v4.26.6 (inactive)
minimap-cursorline, v0.2.0 (inactive)
minimap-find-and-replace, v4.5.1 (inactive)
minimap-git-diff, v4.3.1 (inactive)
minimap-hide, v0.3.0 (inactive)
minimap-highlight-selected, v4.5.0 (inactive)
minimap-linter, v1.6.0 (inactive)
minimap-split-diff, v0.3.2 (inactive)
monokai-seti, v0.7.0 (inactive)
ocaml-indent, v0.5.1 (inactive)
pigments, v0.38.0 (inactive)
project-plus, v0.9.0 (inactive)
python-indent, v1.0.0 (inactive)
python-tools, v0.6.9 (inactive)
Repl, v0.5.0 (inactive)
rest-client, v1.3.1 (inactive)
set-syntax, v0.3.2 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.4.0 (inactive)
smart-tags, v0.1.5 (inactive)
sort-lines, v0.14.0 (inactive)
split-diff, v1.1.1 (inactive)
sync-settings, v0.8.1 (inactive)
todo-show, v1.9.0 (inactive)
trailing-semicolon, v1.1.0 (inactive)
tree-view-git-status, v1.3.0 (inactive)
tree-view-open-files, v0.3.0 (inactive)
vim-mode-plus, v0.80.0 (inactive)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (inactive)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.14.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.33.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.43.2 (inactive)
bracket-matcher, v0.85.1 (inactive)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.2.0 (inactive)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.1 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.5 (inactive)
status-bar, v1.6.0 (inactive)
styleguide, v0.48.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.211.1 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.1 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)

# Dev
No dev packages
```

**Comment by godart** [comment]
Is this a duplicate of #1?

**Comment by pvergara** [comment]
same old same old:

[Enter steps to reproduce:]

1.Atom beta recently installed.
2. Install the atom-ide-ui, and then this one and them, PUUUUMM

**Atom**: 1.21.0-beta2 x64
**Electron**: 1.6.9
**OS**: Ubuntu 17.04
**Thrown From**: [atom-languageclient](https://github.com/OmniSharp/atom-languageclient) package 1.0.7


### Stack Trace

Failed to load the atom-languageclient package

```
At Cannot find module '/home/pvergara/.atom/packages/atom-languageclient/dist/index'

Error: Cannot find module '/home/pvergara/.atom/packages/atom-languageclient/dist/index'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom-beta/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom-beta/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-languageclient/index.js:7:22)
    at /packages/atom-languageclient/index.js:10:3)
    at Module.get_Module._compile (/usr/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/usr/share/atom-beta/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom-beta/resources/app/src/package.js:903:35)
    at /usr/share/atom-beta/resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/usr/share/atom-beta/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/usr/share/atom-beta/resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:617:16)
    at PackageManager.loadPackage (/usr/share/atom-beta/resources/app/src/package-manager.js:550:25)
    at PackageManager.activatePackage (/usr/share/atom-beta/resources/app/src/package-manager.js:684:23)
    at /usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/usr/share/atom-beta/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/usr/share/atom-beta/resources/app/src/buffered-process.js:338:17)
    at /usr/share/atom-beta/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/usr/share/atom-beta/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -9:56.6.0 pane:show-next-recently-used-item (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -9:56.2.0 pane:move-active-item-to-top-of-stack (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  2x -9:01.8.0 symbols-view:toggle-file-symbols (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:52.9.0 settings-view:open (atom-pane.pane.active)
     -8:36.4.0 window:run-package-specs (input.hidden-input)
     -8:34.7.0 core:close (input.hidden-input)
  8x -8:33.6.0 window:run-package-specs (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:24.6.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -8:02.7.0 core:backspace (input.hidden-input)
     -8:00.2.0 core:confirm (input.hidden-input)
     -4:23.7.0 core:paste (input.hidden-input)
     -4:22.7.0 core:backspace (input.hidden-input)
     -4:22.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.4.0 
atom-languageclient 1.0.7 
```

**Comment by marcomorettim** [comment]
Have this:


**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13
**Thrown From**: [atom-languageclient](https://github.com/OmniSharp/atom-languageclient) package 1.0.7


### Stack Trace

Failed to load the atom-languageclient package

```
At Cannot find module '/Users/marcomoretti/.atom/packages/atom-languageclient/dist/index'

Error: Cannot find module '/Users/marcomoretti/.atom/packages/atom-languageclient/dist/index'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-languageclient/index.js:7:22)
    at /packages/atom-languageclient/index.js:10:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:903:35)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:158:34
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:144:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:617:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:550:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:684:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  2x -9:59 window:save-all (input.hidden-input)
  3x -4:55.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-beautify 0.30.5 
atom-ide-ui 0.5.2 
atom-languageclient 1.0.7 
atom-live-server 2.2.0 
autoprefixer 3.7.1 
busy-signal 1.4.3 
closure-linter 0.2.5 
color-gutter 0.3.1 
coverage-gutter 0.19.0 
emmet 2.4.3 
file-icons 2.1.13 
highlight-selected 0.13.1 
ide-csharp 0.6.0 
ide-flowtype 0.17.4 
ide-java 0.6.6 
ide-php 0.6.9 
ide-typescript 0.6.2 
intentions 1.1.5 
language-puppet 0.23.0 
language-rust 0.4.12 
linter 2.2.0 
linter-clang 4.1.2 
linter-codscriptizer 0.2.0 
linter-cpplint 2.0.1 
linter-csslint 2.0.0 
linter-dekiscript 0.1.2 
linter-erb 1.1.0 
linter-flake8 2.2.1 
linter-gjslint 1.5.2 
linter-hlint 2.0.0 
linter-htmlhint 1.3.4 
linter-js-yaml 1.2.8 
linter-jscs 4.1.3 
linter-jshint 3.1.6 
linter-jsl 0.0.1 
linter-lsc 2.4.0 
linter-lua 1.0.4 
linter-mcs 0.2.0 
linter-metascript 0.0.5 
linter-pep8 0.0.5 
linter-php 1.5.1 
linter-puppet-lint 0.8.3 
linter-pycodestyle 2.1.3 
linter-pyflakes 0.3.2 
linter-rst 0.0.3 
linter-rust 0.8.0 
linter-scalac 1.4.4 
linter-scss-lint 3.1.1 
linter-tidy 2.3.1 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-pigments 0.2.2 
pigments 0.40.2 
seti-syntax 1.1.3 
seti-ui 1.9.0 
todo 0.6.0 
unity-dark-ui 2.0.9 
```

**Comment by meteortears** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.0-beta1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-languageclient](https://github.com/OmniSharp/atom-languageclient) package 1.0.7


### Stack Trace

Failed to load the atom-languageclient package

```
At Cannot find module 'C:\Users\Administrator\.atom\packages\atom-languageclient\dist\index'

Error: Cannot find module 'C:\Users\Administrator\.atom\packages\atom-languageclient\dist\index'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.0-beta1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-languageclient/index.js:7:22)
    at /packages/atom-languageclient/index.js:10:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/package.js:937:35)
    at ~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/package.js:160:34
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/package-manager.js:551:25)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/src/package-manager.js:244:29)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.23.0-beta1/resources/app/node_modules/settings-view/lib/package-card.js:361:31)
```

### Commands

```
     -2:06.9.0 github:view-unstaged-changes-for-current-file (div.line)
     -1:26.4.0 core:confirm (input.hidden-input)
     -1:05.3.0 core:paste (input.hidden-input)
     -1:04.8.0 core:confirm (input.hidden-input)
     -1:03.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
advanced-new-file 0.5.0 
advanced-open-file 0.16.7 
api-docs 0.0.6 
atom-beautify 0.30.6 
atom-clock 0.1.15 
atom-css-comb 3.3.1 
atom-html-preview 0.2.2 
atom-ide-ui 0.6.0 
atom-languageclient 1.0.7 
atom-minify 0.8.0 
atom-ternjs 0.18.3 
atom-typescript 11.0.10 
atomic-chrome 0.3.3 
autoclose-html 0.23.0 
autocomplete-modules 1.8.0 
autocomplete-paths 2.12.1 
autoprefixer 3.7.1 
busy-signal 1.4.3 
color-picker 2.2.5 
context-menu-manager 0.2.0 
css-snippets 1.1.0 
csscomb 0.3.1 
docblockr 0.13.2 
editor-stats 0.17.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.13 
file-types 0.5.5 
git-log 0.4.1 
git-plus 7.10.0 
git-time-machine 1.5.9 
grunt-runner 0.14.0 
hey-pane 1.1.0 
hyperclick 0.0.0 
ide-java 0.6.7 
ide-php 0.6.10 
ide-typescript 0.7.0 
intentions 1.1.5 
jade-beautify 0.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
js-hyperclick 1.12.2 
jsformat 0.9.3 
jshint 1.8.6 
language-babel 2.78.0 
language-cshtml 0.3.0 
language-jade 0.7.2 
language-javascript-jsx 0.3.7 
linter 2.2.0 
linter-csslint 2.0.0 
linter-jshint 3.1.6 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
markdown-format 2.5.1 
markdown-preview-plus 2.4.16 
markdown-toc 0.4.2 
minimap 4.29.7 
minimap-pigments 0.2.2 
pigments 0.40.2 
pretty-json 1.6.4 
project-manager 3.3.5 
project-viewer 1.2.5 
px2rem-plus 0.3.1 
react-snippets 1.0.0 
regex-railroad-diagram 0.19.4 
release-notes 0.53.0 
Remote-FTP 1.3.1 
script 3.17.3 
seti-ui 1.9.0 
simplified-chinese-menu 5.3.5 
sort-lines 0.18.0 
sync-settings 0.8.3 
tab-switcher 1.5.6 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
tree-view-finder 0.2.1 
tree-view-git-status 1.4.0 
wordpress-api 1.2.2 
```

**Comment by applicato** [comment]
almost same thing
